export const gossips = [
  `Oasis star Noel Gallagher used to gorge on Greggs pastries and donuts every day`,
  `Lea Michele's lookalike Monica Moskatow says Glee star called her ugly`,
  `WE PAY FOR JUICY INFO!`,
  `Trainer to Hollywood's biggest stars reveals how to get an A-list body`,
  `Ed Sheeran comes out of music retirement to write brand new song`,
  `Kylie Jenner & Travis Scott’s breakup timeline`,
  `Quiet on the set: temper tantrums stars hope you forget`,
  `The style & grace of Chloë Grace Moretz: her top 20 red carpet looks`,
  `Paulina Porizkova feels betrayed after being cut out of husband Ric Ocasek's will`,
  `From too hot to not: Paris Hilton and Chris Zylka's relationship history`,
  `No bite in the big apple? Celine Dion looks scary skinny in New York`,
  `Jennifer Aniston and Brad Pitt relationship timeline`,
  `They shouldn’t have said that: 10 celebrity rants heard around the world`,
  `The most intense celebrity fights on set`,
  `The 18 most bitter real housewives feuds`,
  `Tristan Thompson's remarkable transformation from skinny teen to hulking NBA ace`,
  `Kim Kardashian 'considers leaving home' with Kanye West to 'save marriage'`,
]
