#!/usr/bin/env bash

# Install Exam app

script_dir="$(cd -P "$(dirname "$BASH_SOURCE")" && pwd)"
cd $script_dir
. set.sh

wget https://github.com/01-edu/public/releases/download/exam/exam.1.0.0.AppImage -O /usr/local/bin/exam.1.0.0.AppImage
chmod +x /usr/local/bin/exam.1.0.0.AppImage

cat <<EOF> /home/student/.local/share/applications/appimagekit-exam.desktop
[Desktop Entry]
Name=exam
Comment=the exam client
Exec="/usr/local/bin/exam.1.0.0.AppImage" %U
Terminal=false
Type=Application
Icon=appimagekit-exam
StartupWMClass=exam
X-AppImage-Version=1.0.0
MimeType=x-scheme-handler/exam;
Categories=Utility;
X-AppImage-BuildId=1RHp8aPhkSgD1PXGL1NW5QDsbFF
X-Desktop-File-Install-Version=0.23
X-AppImage-Comment=Generated by /tmp/.mount_exam.1PqfsDP/AppRun
TryExec=/usr/local/bin/exam.1.0.0.AppImage
EOF
chown student:student /home/student/.local/share/applications/appimagekit-exam.desktop

sudo -iu student xdg-mime default appimagekit-exam.desktop x-scheme-handler/exam
