name: Docker Image CI

on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build the Sh Docker image
        run: |
          docker build sh/tests/ --file sh/tests/Dockerfile --tag ghcr.io/01-edu/test-sh:latest
          docker push ghcr.io/01-edu/test-sh:latest

      - name: Build the JS Docker image
        run: |
          docker build js/tests/ --file js/tests/Dockerfile --tag ghcr.io/01-edu/test-js:latest
          docker push ghcr.io/01-edu/test-js:latest

      - name: Build the DOM Docker image
        run: |
          docker build . --file dom/Dockerfile --tag ghcr.io/01-edu/test-js:latest
          docker push ghcr.io/01-edu/test-js:latest
